---
- name: Add apt list for bazel
  copy:
    dest: /etc/apt/sources.list.d/bazel.list
    content: 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8'
    mode: '0644'

- name: Add apt key for bazel
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    state: present

- name: Install packages
  apt:
    name:
      - openjdk-11-jdk
      - bazel
    update_cache: yes
